### PR TITLE
feat: add home page

### LINKED ISSUE #1: chore: custom breakpoints in tailwind config with other repo standards
1. tailwind.config.js

> It is better if we add custom breakpoints.

```javascript
      screens: {
        xs: '200px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        // 2xl: '1536px',
      },
```      
      
2. Since this is going to be public at some point, so it will be better if we can add basic standards like
   - Security.md
   - CODE_OF_CONDUCT.md

3. I will make separate issues for completing different sections of the website as per figma design.

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
Please don't merge.

It hasn't been completed.

closes #1 

## Changes

localhost_3000_

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
I'm also adding changes to resolves #1 here.

**Comment by Anmol-Baranwal** [comment]
@mkubdev @vinzvinci 
You can see the structure.

> Used data to avoid duplicate code

| Example1 | Example2 |
|:-----------:|:-----------:|
| image | image |

| xs | sm | md | lg |
|--------|--------|--------|--------|
| localhost_3000_ (1)  | localhost_3000_ (2) | localhost_3000_ (3) | localhost_3000_ (4) |

**Review by vinzvinci — COMMENTED** [review]
I think we can use **accordion** in the footer, but I think it's good to create separate issue and pr for this?

**Comment by Anmol-Baranwal** [comment]
I don't think an accordion is a good idea.
Suppose you are a user and you want to quickly navigate somewhere or find a contact.

In the current version, or without an accordion, it would be easily found.
While with an accordion, you would first need to check which accordion has the main link, which would add at least two extra clicks.

So, I wouldn't prefer it. Nowadays, I've seen good organizations even avoid accordions in FAQs. That does improve UX.

What do you think?

**Comment by vinzvinci** [comment]
Yeah that make sense.

**Comment by Anmol-Baranwal** [comment]
> Yeah that make sense.

I think, it is fine either way. On mobile, it is easy to get the nav so even if the footer is in accordion, it wouldn't be hard. Totally depends on your preference.

**Comment by vinzvinci** [comment]
> I think, it is fine either way. On mobile, it is easy to get the nav so even if the footer is in accordion, it wouldn't be hard. Totally depends on your preference.

If I were to decide, I would prefer an accordion for mobile, similar to what [Appwrite](https://appwrite.io/) uses. However, since our landing page isn't very long, we can stick with the default design you have already implemented. When we add more sections to our landing page in the future, we can then decide to incorporate the accordion. What do you think?

**Comment by Anmol-Baranwal** [comment]
> If I were to decide, I would prefer an accordion for mobile, similar to what [Appwrite](https://appwrite.io/) uses. However, since our landing page isn't very long, we can stick with the default design you have already implemented. When we add more sections to our landing page in the future, we can then decide to incorporate the accordion. What do you think?

Yep, whatever you feel is right. It wouldn't matter much for initial structure as far as I believe.

**Comment by mkubdev** [comment]
I made the current changes:
- As you added `container` into page.tsx as a parent, I removed unnecessary padding/margin, and used `mx-auto` to center contents.
- Refactored the footer into a `site-footer.tsx` component since it's contained within the parent layout, eliminating the need to add it on every page.
- Uniformized all titles by removing `h1` to match semantic structure; replaced with `h2` since `h1` should be exclusively used in the hero component.
- Uniformized responsive.
- Standardized subtitle styling for consistency.
- Replaced grids for `benefits` component with simple `flex` col, making it much simpler to manage for 4 cols imo.
- Ensured that every component fits into the parent container for a cohesive layout.

**Review by vinzvinci — COMMENTED** [review]
The changes looks good 💯

**Review by mkubdev — APPROVED** [review]
Hi, lgtm!

**Pull request merged**
