### PR TITLE
chore: add correct guidlify logo in different screen devices

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
@mkubdev 
I've made the necessary PR.

And I've undo the changes, and fix the guidlify logo on the landing page so that this PR can be merged.

> small and higher
image

> extra small devices
image

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
I wonder why deployment is failing.

There are no errors:
image

Let me know the log status in vercel build and I'll fix them.

**Comment by vinzvinci** [comment]
Amazing!! I will help to make it responsive, but not for now, super busy..

**Review by mkubdev — CHANGES_REQUESTED** [review]
Hey @Anmol-Baranwal ! This is veryyyyyy awesome PR ! I can help too with responsivness but it's a huge addition based on our Figma design, code is very clean. Unfortunatly we can't merge it as it's code for the webapp [Guildify/guidlify](https://github.com/Guidlify/guidlify) 😅 We are on the landing/documentation repository.

I'll let you open a new PR on the right repository when you have time, I know you're in the exam period so priority first 🙏

Have a good day!

**Comment by vinzvinci** [comment]
oh yep.. my bad as well.. I forgot this should be on other repo.

**Comment by Anmol-Baranwal** [comment]
@mkubdev 
Should I close this PR?

There are some minor changes, and I've undo the changes (for app repo).

Please close this PR if needed :)

**Comment by vinzvinci** [comment]
I think we can close this

**Pull request closed without merging**
