### PR TITLE
feat: add event locations section

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
There are two variations of the card:

   - Only subtext
image

   - With heading
image

- Responsive styling using media queries in `globals.css`
- Pause animation state on hover
- Scaling of image to 105% on hover

> @mkubdev @vinzvinci 
Please check.

I tried to implement what darkterminal suggested. Maybe you can refactor the code.

### CODE REVIEW

**Comment by darkterminal** [comment]
:clap: Need one more step for the slider to :rocket: :tada:

**Review by vinzvinci — COMMENTED** [review]
dam Anmol, I love it🔥

**Comment by Anmol-Baranwal** [comment]
> 👏 Need one more step for the slider to 🚀 🎉

Yes, we will do it. 😅

**Comment by darkterminal** [comment]
I will try to add fix for the slider :eyeglasses:

**Comment by Anmol-Baranwal** [comment]
> I will try to add fix for the slider 👓

Yeah, please :)

**Review by mkubdev — APPROVED** [review]
LGTM 🚀

**Pull request merged**
